Web.Application/Controllers/CountdownController.cs
using Newtonsoft.Json;
using Redmine.Net.Api;
using Redmine.Net.Api.Types;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WBI.Model.DomainModel.TBL_ProjectTicket;
using WBI.Model.ViewModel;
using Web.Application.EDMX;

namespace Web.Application.Controllers
{
    public class CountdownController : Controller
    {
        // GET: Countdown


        public static List<Dictionary<string, string>> GlobalIssues;

        public ActionResult Index()
        {

           


            return View();
        }




        public JsonResult getAllProject() {


            Dictionary<string, List<Dictionary<string, string>>> issuesDictionary = new Dictionary<string, List<Dictionary<string, string>>>();

            List<Dictionary<string, string>> ListProject = new List<Dictionary<string, string>>();
            List<Dictionary<string, string>> ListDictionary = new List<Dictionary<string, string>>();



            try
            {

                string username = "anthony.najour";
                string password = "123456";

                var url = FirstWebApp.Globals.Configuration.REDMINE;

                var manager = new RedmineManager(url, username, password);
                var user = manager.GetCurrentUser();

                var parameters = new NameValueCollection { { "status_id", "*" } };

                var table = manager.GetObjects<Project>(parameters);


                foreach (var p in table)
                {
                    try
                    {

                        Dictionary<string, string> DictionaryProject = new Dictionary<string, string>();

                        DictionaryProject.Add("ProjectId", p.Id == -1 ? "" : "" + p.Id);


                        DictionaryProject.Add("ProjectName", p.Name == null ? "" : p.Name);
                       









                        ListDictionary.Add(DictionaryProject);
                    }
                    catch (Exception ex)
                    {

                    }

                }


                GlobalIssues = ListDictionary;


          ListProject = GlobalIssues.GroupBy(x => x["ProjectId"])
                             .Select(grp => grp.First())
                              .ToList();










            }
            catch { }


            issuesDictionary.Add("data", ListProject);



            issuesDictionary.Reverse();

            var jsonResult = JsonConvert.SerializeObject(issuesDictionary);


            return Json(jsonResult, JsonRequestBehavior.AllowGet);



        }





        [HttpPost]
        public string AddProjectTicket(int projectTicketid, int projectid, string projectname, string desc , string date)
        {
            try
            {
                using (
                    RedmineEntities RedmineEntity = new RedmineEntities())
                {
                    TBL_ProjectTicket ProjectTicket = new TBL_ProjectTicket();

                    ProjectTicket.TBL_ProjectTicket_ID = projectTicketid;
                    ProjectTicket.TBL_ProjectID = projectid;
                    ProjectTicket.TBL_ProjectName = projectname;
                    ProjectTicket.TBL_Project_Description = desc;
                    ProjectTicket.TBL_ProjectTicket_date = date;
                    ProjectTicket.TBL_ProjectTicket_isActive = true;


                    RedmineEntity.TBL_ProjectTicket.Add(ProjectTicket);

                    RedmineEntity.SaveChanges();

                    return "Success";
                }
            }
            catch
            {
                return "An Error has occured";
            }

        }


        [HttpPost]
        public JsonResult GetProjectTicket()
        {
            Dictionary<string, List<TBL_ProjectTicket>> Dictionary = new Dictionary<string, List<TBL_ProjectTicket>>();

            TBL_ProjectTicket ProjectsAvailable = new TBL_ProjectTicket();
            List<TBL_ProjectTicket> ListProjectsAvailable = new List<TBL_ProjectTicket>();

            using (RedmineEntities RedmineEntity = new RedmineEntities())
            {
                ListProjectsAvailable = RedmineEntity.TBL_ProjectTicket.ToList();
            }




            Dictionary.Add("data", ListProjectsAvailable);



            var jsonResult = JsonConvert.SerializeObject(Dictionary);




            return Json(jsonResult, JsonRequestBehavior.AllowGet);
        }









    }
}

Web.Application/Views/Countdown/Index.cshtml
@{

    ViewBag.Title = "Countdown Page";

    Layout = "~/Views/Shared/_LandingLayout.cshtml";
}


<!-- BEGIN PAGE TITLE-->
<h1 class="page-title">
    Admin Dashboard
    <small>project statistics</small>
</h1>
<!-- END PAGE TITLE-->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="index.html">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Dashboard</span>
        </li>
    </ul>
  
</div>

<div class="row">
    <div class="col-lg-12 col-xs-12 col-sm-12">
        <div class="portlet light " >
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject bold uppercase font-dark">Tasks Countdown</span>
                    @*<span class="caption-helper">Percentage stats...</span>*@
                </div>
                <div class="actions">
                    @*<a class="btn btn-circle btn-icon-only btn-default" href="#">
                            <i class="icon-cloud-upload"></i>
                        </a>
                        <a class="btn btn-circle btn-icon-only btn-default" href="#">
                            <i class="icon-wrench"></i>
                        </a>
                        <a class="btn btn-circle btn-icon-only btn-default" href="#">
                            <i class="icon-trash"></i>
                        </a>*@
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="#"> </a>
                </div>
            </div>
            <div class="portlet-body">
             
                <div @*id="dashboard_amchart_2"*@ class="mapChart"  >

                    <div class="col-md-3">
                        <label for="select2-single-input-sm" class="control-label">Project</label>
                        <select id="selectprojectname" class="form-control input-sm select2-multiple">
                          
                           
                               
                       

                        </select>
                    </div>
                    <div class="col-md-3">
                        <label for="select2-single-input-sm" class="control-label">desciprtion</label>

                        <input type="text" value="" class="form-control" placeholder="description ..." id="description" />

                    </div>



                    <div class="col-md-3">

                        <label for="select2-single-input-sm" class="control-label">Datetime</label>
                   

                            <div class="input-group date form_datetime">
                                <input id="datetimepicker" type="text" size="16" readonly class="form-control">
                                <span class="input-group-btn">
                                    <button class="btn default date-set" type="button">
                                        <i class="fa fa-calendar"></i>
                                    </button>
                                </span>
                            </div>
                   







                    </div>

                    <div class="col-md-3">

                        <label for="select2-single-input-sm" class="control-label">add</label>

                        <br>
                        <button id="btn-add-project" type="button" class="btn btn-circle red">+</button>
                    </div>
                    <br>

                    <div  id="addproject">

                    <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3" style="padding:30px 15px 0 15px">

                        <img src="~/Content/Metronic/assets/global/img/loading-spinner-grey.gif" alt="loading" width="50" height="50">

                    </div>
                       



                    </div>
             



                </div>
            </div>
        </div>


    </div>

   

            </div>










            <script src="~/Scripts/Metronic/jquery.min.js" type="text/javascript"></script>


            <script>

                var projectColorarray = []

                $(document).ready(function () {
                    getAllProject();
                   

                });


                function getAllProject() {



                    var listhexColor = [];

                    listhexColor.push("#000000");
                    listhexColor.push("#ec0000");
                    listhexColor.push("#007500");
                    listhexColor.push("#88acab");
                    listhexColor.push("#9b357b");
                    listhexColor.push("#ffcc00");
                    listhexColor.push("#b76e79");
                    listhexColor.push("#5e0303");
                    listhexColor.push("#ff1493");
                    listhexColor.push("#36c6d3");


                    $.ajax({
                        url: '@Url.Action("getAllProject", "Countdown")',
                        type: 'GET',
                        contentType: "application/json",
                        dataType: "json",
                        error: function () {

                            alert("error")
                        },
                        success: function (data) {

                            //   alert("success");

                            var html = "";


                            var obj = JSON.parse(data);



                            $.each(obj.data, function (key, value) {
                                var projectColorob = {}

                                projectColorob.ProjectId = value.ProjectId;

                                projectColorob.ProjectColor = listhexColor.pop();


                                projectColorarray.push(projectColorob);


                                html += '<option value="' + value.ProjectId + '">' + value.ProjectName + '</option>';

                            });


                            $("#selectprojectname").html("");
                            $("#selectprojectname").append(html);

                            GetProjectTicket();

                        }
                    });
                }

                $("#btn-add-project").click(function () {


                     var e = document.getElementById("selectprojectname");
                   var projectName = e.options[e.selectedIndex].text;
            

                   var projectid = $("#selectprojectname").val();

                  

                    var description = $("#description").val();
                    var dateString = $("#datetimepicker").val();

                //    alert(projectid);

                    if (projectid != "" && description != "" && dateString != "") {



                        var obj = {};

                        obj.projectTicketid = 0;
                        obj.projectid = Number(projectid);
                        obj.desc = description;
                        obj.date = dateString;

                        obj.projectname = projectName;

                     

                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("AddProjectTicket", "Countdown")',
                            data: JSON.stringify(obj),
                            dataType: "text",
                            contentType: "application/json; charset=utf-8",

                            error: function () {

                                alert("error")
                            },

                            success: function (data) {
                          



                                GetProjectTicket();


                                $("#selectprojectname").val(projectid);
                                $("#description").val('');
                                $("#datetimepicker").val('');

                     }
                        });


              }
                    else {

                        alert("All Field are required");

                    }


   });







  </script>










<script>

    function GetProjectTicket() {
 
        var obj = {};

        $.ajax({
            type: "POST",
            url: '@Url.Action("GetProjectTicket", "Countdown")',
            data: JSON.stringify(obj),
            dataType: "json",
            contentType: "application/json; charset=utf-8",

            error: function () {

                alert("error")
            },

            success: function (data) {
                // $("#mainSection").html(r.d);

             //   alert("yes");
             //   alert(JSON.stringify(data));




                // $("#mainSection").html(r.d);

              //  alert("yes");
              //  alert(data);

                
                var object = JSON.parse(data);


               
                var html = "";

                $.each(object.data, function (key, value) {
                 
                    
                  //  alert("yes");

                 
                    var dateString = value.TBL_ProjectTicket_date;

                    var dateWithoutSpace = dateString.replace(/ /g, ''); //to remove all space

                    var different = moment(new Date(dateWithoutSpace)).from(new Date());

                    //  alert(different);




                    //  alert(JSON.stringify(projectColorarray));


                    var getColor = projectColorarray.filter(function (el) {

                        return el.ProjectId == value.TBL_ProjectID;
                    });
               

                    var color = getColor.map(a => a.ProjectColor);

                  

                    html += '<div  class="col-xs-12 col-sm-3 col-md-3 col-lg-3" style="padding:30px 15px 0 15px">';

                    html += '<div class="widget-thumb widget-bg-color-white text-uppercase margin-bottom-20 bordered">';
                    html += '<h4 class="widget-thumb-heading" style="word-break:break-all; font-size:25px">' + value.TBL_Project_Description + '</h4>';
                    html += '<div class="widget-thumb-wrap">';
                    html += '<i class="widget-thumb-icon  icon-layers" style="background:' + color + '"></i>';
                    html += '<div class="widget-thumb-body" id="divallticket">';
                    html += '<span class="widget-thumb-subtitle">' + value.TBL_ProjectName + '</span>';
                    html += ' <span id="spanallticket" class="widget-thumb-body-stat" >' + different + '</span>';
                    html += '</div>';
                    html += '</div>';
                    html += ' </div>';

                    html += '</div>';

                $("#addproject").html('');

                     $("#addproject").append(html);



                });

              }


        });


    }

</script>