Web.Application/Controllers/TicketsController.cs
using Newtonsoft.Json;
using Redmine.Net.Api;
using Redmine.Net.Api.Types;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Web.Application.Models;
using Web.Application.Session;



namespace Web.Application.Controllers
{
    public class TicketsController : Controller
    {
 
        public ActionResult Index()
        {
           return View();
                }
        public ActionResult InfoTickets()
        {
            return View();
        }

        public JsonResult getAllUsers1(string projectName, string format)
        {
         string username = "anthony.najour";
            string password = "123456";
            var url = FirstWebApp.Globals.Configuration.REDMINE;

            var manager = new RedmineManager(url, username, password);

            var user = manager.GetCurrentUser();

            var parameters = new NameValueCollection { { "status_id", "*" } };

            var AllData = manager.GetObjects<Issue>(parameters).ToList();

           List<string> users = new List<string>();

          foreach (var Issue in AllData)
            {
                try
                {
                   users.Add(Issue.AssignedTo.Name);
                    }
                       catch (Exception ex) { }
                                          }
              List<string> usersdistinct = users.Distinct().ToList();
                var jsonResultEmpls = JsonConvert.SerializeObject(usersdistinct);
               return Json(jsonResultEmpls, JsonRequestBehavior.AllowGet);
          
            }









        public JsonResult getTicketByUser (string Name)
        {
            string username = "anthony.najour";
            string password = "123456";

            var url = FirstWebApp.Globals.Configuration.REDMINE;

            var manager = new RedmineManager(url, username, password);

            var user = manager.GetCurrentUser();

            var parameters = new NameValueCollection { { "status_id", "*" } };

            var AllData = manager.GetObjects<Issue>(parameters).ToList();

           List<string> UserProjects1 = new List<string>();
           // List<string> UserProjects2 = new List<string>();
 
            List<string> users = new List<string>();

            foreach (var Issue in AllData)
            {
                try
                {
                    //if (Issue.AssignedTo.Name == "Jihad Fares")
                    //{
                    //    UserProjects1.Add(Issue.AssignedTo.Name + ',' + Issue.Project.Id);
                    //}
                    if (Issue.AssignedTo.Name == Name)
                    {
                        UserProjects1.Add(Issue.Project.Id.ToString());
                    
   }             }


                catch (Exception ex) { }
                        }

            string UserProjects = string.Join(",", UserProjects1);
           // string UserProjects22 = string.Join(",", UserProjects2);

            var NbrUserProjectsB = UserProjects1.GroupBy(x => x)
              .Where(g => g.Count() > 1)
              .Select(y => new { Element = y.Key, Counter = y.Count() })
              .ToList();
            ////var NbrUserProjectsB = UserProjects2.GroupBy(x => x)
            ////  .Where(g => g.Count() > 1)
            ////  .Select(y => new { Element = y.Key, Counter = y.Count() })
            ////  .ToList();
            // int distinctCount = UserProjects1.Distinct().Count();
            //List<string> usersdistinct = users.Distinct().ToList();

            //var jsonResultEmpls = JsonConvert.SerializeObject(usersdistinct);

            var jsonNbrUserProjectsB = JsonConvert.SerializeObject(NbrUserProjectsB);


            //var result = new { jsonResultEmpls, jsonNbrUserProjectsB };
            return Json(jsonNbrUserProjectsB, JsonRequestBehavior.AllowGet);

    }








        public JsonResult getInfTicketsByUser(string Name, int Id)
        {
            string username = "anthony.najour";
            string password = "123456";

            var url = FirstWebApp.Globals.Configuration.REDMINE;

            var manager = new RedmineManager(url, username, password);

            var user = manager.GetCurrentUser();

            var parameters = new NameValueCollection { { "status_id", "*" } };

            var AllData = manager.GetObjects<Issue>(parameters).ToList();

            //List<string> InfTicketsId = new List<string>();
            List<Dictionary<string, string>> InfTicketsId = new List<Dictionary<string, string>>();
            // List<string> UserProjects2 = new List<string>();

            List<string> users = new List<string>();


            foreach (var Issue in AllData)
            {
                try
                {
                    
                    if (Issue.AssignedTo.Name == Name & Issue.Project.Id == Id)
                    {

                        //InfTicketsId.Add(Issue.Id + Issue.Project.Id+Issue.Author.Name+Issue.Category+Issue.Priority.Name+Issue.StartDate+Issue.Status+Issue.Subject);
                        Dictionary<string, string> MyList1 = new Dictionary<string, string>();

                        MyList1.Add("ID", Issue.Id.ToString());
                        MyList1.Add("AssignedTo", Issue.AssignedTo.Name);
                        MyList1.Add("Status", Issue.Status.ToString());
                        MyList1.Add("Project", Issue.Project.Name);
                        MyList1.Add("Author", Issue.Author.Name);


                        InfTicketsId.Add(MyList1);
                    }
                }


                catch (Exception ex) { }
            }

            //string UserProjects = string.Join(",", InfTicketsId);
            

            //var jsonInfTicketsId = JsonConvert.SerializeObject(InfTicketsId);

            return Json(InfTicketsId, JsonRequestBehavior.AllowGet);

        }











    } }


  

    
    

Web.Application/Views/Tickets/InfoTickets.cshtml
@{
    Layout = "~/Views/Shared/_LandingLayout.cshtml";
}




@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<!-- BEGIN PAGE TITLE-->
<h1 class="page-title" text-align center  ;
    >
    Tickets Employee

</h1>
<!-- END PAGE TITLE-->
<style>


    h1 {background-color: #d7f2f0
    }
table{
    width: 100%;
 
}
th, td {
    background-color: rgba(241, 203, 203, 0.63);
}
</style>

<table class="table table-bordered table-condensed table-hover table-striped" id="idtable" >
        <thead>
            <tr>
                <th >Employee</th>
                <th id="Cell4" > </th>
            </tr>
        </thead>

    <tbody id="mydata">  
        <tr id="123" onclick="getFunction(123)">    <td>    PM Tasks Pending:         </td>      <td id="cell1">  </td>           </tr>

        <tr id="128" onclick="getFunction(128)">    <td>    Modular Tasks Pending:    </td>      <td id="cell2">  </td>           </tr>

        <tr id="130" onclick="getFunction(130)">    <td>  Intership Tasks Pending:    </td>      <td id="cell3">  </td>           </tr>

    </tbody>

    </table>

<br />
<br />
<div>
 
   

    <div id="showContent">


        <select id='useresdropdown' onchange='myFunction()' class='form-control'></select>

    </div>
    <div id="showContent1">

    </div>

</div>
<br />
<br />


<table class="table table-bordered table-condensed table-hover table-striped" id="idtable2">
    <thead>
        <tr id="Cell11"> </tr>
        <tr>
            <th>Employee </th>
            <th>Project</th>
            <th>Id Tasks</th>
            <th>Author</th>
            <th>Description </th>
        </tr>
    </thead>



    <tbody id="IdTbody2"></tbody>

</table>
        @*<tr> 
            <td id="cell6">  </td> 
            <td id="cell7">  </td>
            <td id="cell8">  </td>
            <td id="cell9">  </td>
            <td id="cell10">  </td>
            <td id="cell11">  </td>
            <td id="cell12">  </td>  
        </tr>*@

       
    </tbody>

</table>











<script>
    alert("Hello JS");

    $(document).ready(function () {
        $.ajax({
            type: "POST",
            url: '@Url.Action("getAllUsers1", "Tickets")',
            dataType: "json",
            //contentType: "application/json",
            contentType: 'application/json; charset=utf-8',
            error: function () { alert("error") },
            //success: function (result) {

            //    alert(result);
            success: function (jsonResultEmpls) {
                alert(jsonResultEmpls);
                //alert(results.jsonNbrUserProjectsB);
                //var NbrUserProjectsB = JSON.parse(results.jsonNbrUserProjectsB);
                var ResultEmpls = JSON.parse(jsonResultEmpls);

                //$.each(NbrUserProjectsB, function (idx, obj) {
                //    alert(obj);
                //});



               var html;
              // html += "<select id='useresdropdown' onchange='myFunction()' class='form-control'>";

               $.each(ResultEmpls, function (idx, obj) {

                   html += "<option value=" + obj + ">" + obj + "</option>";
               });

              //  html += "</select>";
               $('#useresdropdown').html(html);
                $('#useresdropdown').select2();
            }
        });


    });



    //$('#useresdropdown').change(function (e) {

    //$("#useresdropdown").on('change' ,function (e) {

    function myFunction() {
        var e = $("#useresdropdown").text();

        var ee = document.getElementById("useresdropdown");
        var t=ee.options[ee.selectedIndex].text;
        alert("test");
        alert(t);


      
        var object = {}
        object.Name = t;
        $("#Cell4").text(object.Name);

            $.ajax({
                type: "POST",
                url: '@Url.Action("getTicketByUser", "Tickets")',

                dataType: "json",
                //contentType: "application/json",

                contentType: 'application/json; charset=utf-8',

                data: JSON.stringify(object),

                error: function () { alert("error") },

                success: function (jsonNbrUserProjectsB) { // on success..

                    //alert(jsonNbrUserProjectsB);

var ResulNbrUserProjectsB = JSON.parse(jsonNbrUserProjectsB);

console.log(ResulNbrUserProjectsB);





$.each(ResulNbrUserProjectsB, function (idx, obj) {
    console.log(obj);
    if (obj.Element == "128") {   $("#cell2").text(obj.Counter); }
          else   { $("#cell2").text("0");}

    if (obj.Element == "123") { $("#cell1").text(obj.Counter); }

    if (obj.Element == "130") { $("#cell3").text(obj.Counter); }
           else { $("#cell3").text("0"); }
    

});


              
    

                }


            });
    }














    function getFunction(id) {

        alert(id);
        var ee = document.getElementById("useresdropdown");
        var t=ee.options[ee.selectedIndex].text;
        alert("test");
        alert(t);
      
        var object = {}
        object.Name = t;
        object.id = id;
        alert(object);



        $.ajax({
            type: "POST",
            url: '@Url.Action("getInfTicketsByUser", "Tickets")',

            dataType: "json",
            //contentType: "application/json",

            contentType: 'application/json; charset=utf-8',

            data: JSON.stringify(object),

            error: function () { alert("error") },

            success: function (InfTicketsId) { // on success..

                console.log(InfTicketsId);

                //var ResuljsonInfTicketsId = JSON.parse(jsonInfTicketsId);



                $.each(InfTicketsId, function (idx, obj2) {
                    console.log(obj2);

                    var html2;
                    html2 += "<tr>";
                    html2 += "<td>" + obj2.AssignedTo + "</td>";
                    html2 += "<td>" + obj2.Project + "</td>";
                    html2 += "<td>" + obj2.ID + "</td>";
                    html2 += "<td>" + obj2.Author + "</td>";
                    html2 += "<td>" + obj2.Status + "</td>"

                    html2 += "</tr>";

                    $("#IdTbody2").append(html2);

                });
  }










        });




    


    }









</script> 







               